### ISSUE TITLE
ogg sounds

### ISSUE THREAD

**Issue by Pantyhose-X** [IIIullaIII/jukebox_new#1]
The music I created using [Balabolka](http://balabolka.site/balabolka.htm)
download https://github.com/Pantyhose-X/AllmodsIuse/releases/download/ogg/Captures.zip

Do you need it? You are free to use.
Contact https://rvlt.gg/discover/search?embedded=true&query=minetest

**Comment by IIIullaIII** [comment]
i use audacity i have music but removed in the mod for not implement the license ,i just add traduction from google translate
what audio is in that zip file?
